CREATE TABLE coverage_requests (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  store VARCHAR(32) NOT NULL,
  requested_by_employee_id BIGINT NOT NULL,
  replacement_employee_id BIGINT NULL,
  coverage_type VARCHAR(32) NOT NULL,
  shift_date DATE NOT NULL,
  start_time TIME NULL,
  end_time TIME NULL,
  shift_type VARCHAR(32) NOT NULL,
  position VARCHAR(64) NOT NULL,
  reason TEXT NULL,
  manager_note TEXT NULL,
  status VARCHAR(32) NOT NULL,
  approved_by_employee_id BIGINT NULL,
  approved_at TIMESTAMP(6) NULL,
  reviewed_by_employee_id BIGINT NULL,
  reviewed_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  INDEX ix_coverage_requested_by (requested_by_employee_id, shift_date),
  INDEX ix_coverage_replacement (replacement_employee_id, shift_date),
  INDEX ix_coverage_pool (coverage_type, status, shift_date),
  INDEX ix_coverage_status_date (status, shift_date),
  INDEX ix_coverage_approved_by (approved_by_employee_id),
  INDEX ix_coverage_reviewed_by (reviewed_by_employee_id),
  CONSTRAINT fk_coverage_requested_by FOREIGN KEY (requested_by_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_coverage_replacement FOREIGN KEY (replacement_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_coverage_approved_by FOREIGN KEY (approved_by_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_coverage_reviewed_by FOREIGN KEY (reviewed_by_employee_id) REFERENCES employees(id),
  CONSTRAINT chk_coverage_type CHECK (coverage_type IN ('PUBLIC', 'DIRECT')),
  CONSTRAINT chk_coverage_status CHECK (status IN ('OPEN', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED')),
  CONSTRAINT chk_coverage_shift_type CHECK (shift_type IN ('LUNCH', 'DINNER', 'DOUBLE')),
  CONSTRAINT chk_coverage_public_open_unclaimed CHECK (coverage_type <> 'PUBLIC' OR status <> 'OPEN' OR replacement_employee_id IS NULL),
  CONSTRAINT chk_coverage_direct_replacement CHECK (coverage_type <> 'DIRECT' OR replacement_employee_id IS NOT NULL),
  CONSTRAINT chk_coverage_not_self_replacement CHECK (replacement_employee_id IS NULL OR replacement_employee_id <> requested_by_employee_id),
  CONSTRAINT chk_coverage_time_order CHECK (start_time IS NULL OR end_time IS NULL OR end_time > start_time)
);

CREATE TABLE coverage_request_audit_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_id BIGINT NOT NULL,
  action VARCHAR(80) NOT NULL,
  actor_employee_id BIGINT NOT NULL,
  actor_name_snapshot VARCHAR(190) NULL,
  requested_by_employee_id BIGINT NULL,
  requested_by_name_snapshot VARCHAR(190) NULL,
  replacement_employee_id BIGINT NULL,
  replacement_name_snapshot VARCHAR(190) NULL,
  store VARCHAR(32) NOT NULL,
  shift_date DATE NOT NULL,
  old_status VARCHAR(32) NULL,
  new_status VARCHAR(32) NOT NULL,
  details TEXT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  INDEX ix_coverage_audit_request (request_id, created_at),
  INDEX ix_coverage_audit_actor (actor_employee_id, created_at),
  CONSTRAINT fk_coverage_audit_request FOREIGN KEY (request_id) REFERENCES coverage_requests(id),
  CONSTRAINT fk_coverage_audit_actor FOREIGN KEY (actor_employee_id) REFERENCES employees(id)
);
