ALTER TABLE inventory_count_sessions
  ADD COLUMN assigned_counter_employee_id BIGINT NULL AFTER created_by_employee_id,
  ADD COLUMN due_date DATE NULL AFTER assigned_counter_employee_id,
  ADD COLUMN due_time TIME NULL AFTER due_date,
  ADD COLUMN started_at TIMESTAMP(6) NULL AFTER due_time,
  ADD COLUMN submitted_by_employee_id BIGINT NULL AFTER completed_at,
  ADD COLUMN submitted_by_name_snapshot VARCHAR(190) NULL AFTER submitted_by_employee_id,
  ADD COLUMN submitted_at TIMESTAMP(6) NULL AFTER submitted_by_name_snapshot,
  ADD COLUMN reviewed_by_employee_id BIGINT NULL AFTER submitted_at,
  ADD COLUMN reviewed_by_name_snapshot VARCHAR(190) NULL AFTER reviewed_by_employee_id,
  ADD COLUMN reviewed_at TIMESTAMP(6) NULL AFTER reviewed_by_name_snapshot,
  ADD COLUMN locked_by_employee_id BIGINT NULL AFTER reviewed_at,
  ADD COLUMN locked_by_name_snapshot VARCHAR(190) NULL AFTER locked_by_employee_id,
  ADD COLUMN locked_at TIMESTAMP(6) NULL AFTER locked_by_name_snapshot,
  ADD COLUMN override_reason TEXT NULL AFTER locked_at,
  ADD COLUMN cancelled_at TIMESTAMP(6) NULL AFTER override_reason,
  ADD KEY ix_inventory_sessions_assigned_counter (assigned_counter_employee_id),
  ADD CONSTRAINT fk_inventory_sessions_assigned_counter FOREIGN KEY (assigned_counter_employee_id) REFERENCES employees(id),
  ADD CONSTRAINT fk_inventory_sessions_submitted_by FOREIGN KEY (submitted_by_employee_id) REFERENCES employees(id),
  ADD CONSTRAINT fk_inventory_sessions_reviewed_by FOREIGN KEY (reviewed_by_employee_id) REFERENCES employees(id),
  ADD CONSTRAINT fk_inventory_sessions_locked_by FOREIGN KEY (locked_by_employee_id) REFERENCES employees(id);

CREATE TABLE order_plan_sessions (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  location_code VARCHAR(32) NOT NULL,
  source_inventory_session_id BIGINT NOT NULL,
  inventory_business_date DATE NOT NULL,
  inventory_completed_by_employee_id BIGINT NULL,
  inventory_completed_by_name_snapshot VARCHAR(190) NULL,
  inventory_completed_at TIMESTAMP(6) NULL,
  business_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_by_employee_id BIGINT NOT NULL,
  assigned_orderer_employee_id BIGINT NULL,
  due_date DATE NULL,
  due_time TIME NULL,
  notes TEXT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL,
  started_at TIMESTAMP(6) NULL,
  submitted_by_employee_id BIGINT NULL,
  submitted_by_name_snapshot VARCHAR(190) NULL,
  submitted_at TIMESTAMP(6) NULL,
  completed_by_employee_id BIGINT NULL,
  completed_by_name_snapshot VARCHAR(190) NULL,
  completed_at TIMESTAMP(6) NULL,
  cancelled_at TIMESTAMP(6) NULL,
  KEY ix_order_plans_location_date (location_code, business_date),
  KEY ix_order_plans_status (status),
  KEY ix_order_plans_assigned_orderer (assigned_orderer_employee_id),
  KEY ix_order_plans_source_inventory (source_inventory_session_id),
  CONSTRAINT fk_order_plans_source_inventory FOREIGN KEY (source_inventory_session_id) REFERENCES inventory_count_sessions(id),
  CONSTRAINT fk_order_plans_inventory_completed_by FOREIGN KEY (inventory_completed_by_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_order_plans_created_by FOREIGN KEY (created_by_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_order_plans_assigned_orderer FOREIGN KEY (assigned_orderer_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_order_plans_submitted_by FOREIGN KEY (submitted_by_employee_id) REFERENCES employees(id),
  CONSTRAINT fk_order_plans_completed_by FOREIGN KEY (completed_by_employee_id) REFERENCES employees(id)
);

CREATE TABLE order_plan_lines (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_plan_session_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  vendor_id BIGINT NOT NULL,
  product_name_snapshot VARCHAR(190) NOT NULL,
  product_code_snapshot VARCHAR(64) NULL,
  vendor_name_snapshot VARCHAR(190) NOT NULL,
  package_specification_snapshot VARCHAR(190) NULL,
  inventory_unit_snapshot VARCHAR(32) NOT NULL,
  order_unit_snapshot VARCHAR(32) NOT NULL,
  unit_price_snapshot DECIMAL(12,2) NULL,
  source_inventory_quantity DECIMAL(12,3) NULL,
  par_level_snapshot DECIMAL(12,3) NULL,
  reorder_point_snapshot DECIMAL(12,3) NULL,
  previous_order_quantity DECIMAL(12,3) NULL,
  suggested_order_quantity DECIMAL(12,3) NULL,
  final_order_quantity DECIMAL(12,3) NULL,
  notes TEXT NULL,
  updated_by_employee_id BIGINT NULL,
  updated_at TIMESTAMP(6) NULL,
  UNIQUE KEY uk_order_plan_lines_plan_product (order_plan_session_id, product_id),
  KEY ix_order_plan_lines_vendor (vendor_id),
  KEY ix_order_plan_lines_product (product_id),
  CONSTRAINT fk_order_plan_lines_plan FOREIGN KEY (order_plan_session_id) REFERENCES order_plan_sessions(id),
  CONSTRAINT fk_order_plan_lines_product FOREIGN KEY (product_id) REFERENCES order_catalog_products(id),
  CONSTRAINT fk_order_plan_lines_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id),
  CONSTRAINT fk_order_plan_lines_updated_by FOREIGN KEY (updated_by_employee_id) REFERENCES employees(id)
);

ALTER TABLE purchase_orders
  ADD COLUMN order_plan_session_id BIGINT NULL AFTER source_inventory_session_id,
  ADD KEY ix_purchase_orders_order_plan (order_plan_session_id),
  ADD CONSTRAINT fk_purchase_orders_order_plan FOREIGN KEY (order_plan_session_id) REFERENCES order_plan_sessions(id);

ALTER TABLE purchase_order_lines
  ADD COLUMN source_inventory_quantity_snapshot DECIMAL(12,3) NULL AFTER unit_price_snapshot,
  ADD COLUMN suggested_order_quantity DECIMAL(12,3) NULL AFTER source_inventory_quantity_snapshot,
  ADD COLUMN final_order_quantity DECIMAL(12,3) NULL AFTER suggested_order_quantity;
